FROM alpine AS dwnld
RUN apk update --no-cache && apk add --no-cache ca-certificates curl
RUN curl https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/5181-9eba8dcc91ee4c6ab009fcf7a47837edf81efd1a/fx.tar.xz | tar xJ -C /srv/.

FROM scratch
COPY --from=dwnld /srv/alpine/. /.

COPY run.sh /opt/cfx-server
RUN apk update && \
    apk add --no-cache tzdata

RUN mkdir -p /usr/local/share/ && touch /usr/local/share/.yarnrc

WORKDIR /opt/cfx-server
CMD ["sh", "run.sh"]
