FROM alpine AS dwnld
RUN apk update --no-cache && apk add --no-cache ca-certificates curl
RUN curl https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/5181-9eba8dcc91ee4c6ab009fcf7a47837edf81efd1a/fx.tar.xz | tar xJ -C /srv/.

FROM scratch
COPY --from=dwnld /srv/alpine/. /.
RUN apk update && \
    apk add --no-cache tzdata

RUN mkdir -p /usr/local/share/ && touch /usr/local/share/.yarnrc

EXPOSE 30120/tcp 30120/udp 40120/tcp

WORKDIR /opt/cfx-server
ENTRYPOINT ""
CMD ""